### ISSUE TITLE
A confusion happened in bash inference_logits_roberta

### ISSUE THREAD

**Issue by cuberJ** [tonytan48/KD-DocRE#10]
Hello, I have a confusion in the script **inference_logits_roberta.sh**. 
The param **--teacher_path** need **roberta-teacher.pt**, but **batch_roberta.sh** output the model named **roberta_model.pt**, and I didn't find the output model named about teacher in the first step
So does **roberta_teacher.pt** means using **roberta_model.pt**?

![image](https://user-images.githubusercontent.com/43082093/180348790-d140c112-296d-4b92-a2fd-f94ef8c57e12.png)

**Comment by tonytan48** [comment]
Hi, thank you for your interest, you are correct in this case, this parameter should be the name of your own saved model in the previous step.
