### ISSUE TITLE
I got the problem about "ZeroDivisionError: float division by zero"

### ISSUE THREAD

**Issue by bitten-littlesuqirrel** [tonytan48/KD-DocRE#11]
Hi, I got the problem which is "ZeroDivisionError: float division by zero" while I run the step3 with  "bash scripts/knowledge_distill_bert.sh "
![image](https://user-images.githubusercontent.com/40733610/185153029-fce214c6-da73-4a1a-9de8-99ab5230258b.png)

I'm confused about that.

**Comment by tonytan48** [comment]
Hi there,
Thank you for your interest. May I know is this bug always the case? or it doest not pop up for some other random seeds. It seems that this bug originates from apex's operation. We used apex-0.1 from and built from their github repository.

**Comment by bitten-littlesuqirrel** [comment]
Yes, you are right. 
The problem lies in the apex.The problem is solved after I changed  "out_scale/grads_have_scale" to "out_scale/(grads_have_scale+float(”1e-8”))"

**Comment by bitten-littlesuqirrel** [comment]
Yes, you are right.
The problem lies in the apex.The problem is solved after I changed "out_scale/grads_have_scale" to "out_scale/(grads_have_scale+float(”1e-8”))".

**Comment by bitten-littlesuqirrel** [comment]
Yes, you are right.
The problem lies in the apex.It is solved after I changed "out_scale/grads_have_scale" to "out_scale/(grads_have_scale+float(”1e-8”))"
