### ISSUE TITLE
the program will always be killed.

### ISSUE THREAD

**Issue by bitten-littlesuqirrel** [tonytan48/KD-DocRE#12]
I'm curious that when I run the step 3, the program will always be killed without any hint.
![1661068595(1)](https://user-images.githubusercontent.com/40733610/185781510-ac489dea-a885-414d-913b-d8c949c22261.png)

**Comment by bitten-littlesuqirrel** [comment]
The program was killed in 39 epoch while the num_train_epochs is 50.0.Then when I set the num_train_epochs to 30,the program was killed in 26 epoch.

**Comment by tonytan48** [comment]
Hi there,
    Thank you for your interest. I have encountered this bug elsewhere, and it may be due to the gpu memory leakage from pytorch. For this stage, I should have change the num_train_epochs to 20, because the max f1 score in this stage (the training corpus is over 100k) typically occurs at earlier epochs, should be lower than 20. You may check your best checkpoints from earlier epochs.  Actually I should set an early-stopping mechanism to save some computing time, I will try to update this part in few days. Thanks again for bringing this up.

**Comment by bitten-littlesuqirrel** [comment]
Thank you for your advice. I look forward to your revised code and your future work.
