### ISSUE TITLE
Question about the focal loss

### ISSUE THREAD

**Issue by RedVelvetCake21** [tonytan48/KD-DocRE#16]
Could you tell me why using (1 + prob_0_gamma) instead of prob_0_gamma in the code of loss1? Thanks a lot!
loss1 = - (log_prob_1 * (1 + prob_0_gamma ) * labels)

**Comment by tonytan48** [comment]
Hi, Thank you for your interest. The 1 here is a factor that I found useful for tuning for precision and recall. In some scenarios, such as training with incomplete annotation, this factor is able to improve the recall without sacrificing much precision.

**Comment by RedVelvetCake21** [comment]
I see!
