### ISSUE TITLE
My reproduction results (with distant supervision) are lower than results in the paper.

### ISSUE THREAD

**Issue by Jize-W** [tonytan48/KD-DocRE#17]
I did not change any hyperparameters and the final results (KD-Rb-l) after step1, 2, 3, and 4 are F1=64.12, Ign_F1=61.96. They are lower than the results reported in the paper: F1=67.12, Ign_F1=65.27.

My reproduction results of each step are:

||F1|             Ign_F1|
|--|--|--|
|step1: teacher       |              62.83      |      60.77|
|step3: student-pretrain    |   59.06         |   49.06|
|step4: student-finetune  |    64.12    |        60.96|

But I tried the given checkpoint and the results are consistent with those in the paper.

My question is: How was the checkpoint trained? Was the finetuned student model treated as a teacher and trained extra rounds through step1, 2, 3, 4? Or trained only one round?

**Comment by tonytan48** [comment]
Hi, our experiments are trained on only one round for the leaderboard submission. Actually, I tried to use the student-finetuned model to train for an extra round with the 67 F1 model, but it cannot exceed the previous best submission. It seems that your reproduction has a lower teacher and finetune stage and higher in student-pretrain stage. Some empirical trick that I found useful is the student-pretrain should have higher recall than precision. Besides, the best checkpoints are typically in the early stage during student-finetune.
