### ISSUE TITLE
ModuleNotFoundError: No module named 'utils'

### ISSUE THREAD

**Issue by moh-yani** [tonytan48/KD-DocRE#5]
Dear,

When we tried to run bash scripts/bathc_roberta.sh we got errors:

File "train.py", line 13, in <module>
    from utils import set_seed, collate_fn, collate_fn_kd, label_collate_fn, get_label_input_ids
ModuleNotFoundError: No module named 'utils'

Anyone knows what happen?

regards,

Mohammad

**Comment by tonytan48** [comment]
Sorry I forgot to upload it, now should be there.

**Comment by moh-yani** [comment]
Thanks Tony,

regards,

Mohammad
