### ISSUE TITLE
ModuleNotFoundError: No module named 'multihead_attention'

### ISSUE THREAD

**Issue by moh-yani** [tonytan48/KD-DocRE#6]
Dear Tony,

I found a new error when I run  bash scripts/batch_roberta.sh:
ModuleNotFoundError: No module named 'multihead_attention'

I changed 
from multihead_attention import MultiheadAttention to from torch_multi_head_attention import MultiHeadAttention 

the error message above does not appear again but, a new error is found:
  File "train.py", line 398, in main                                          │
    model = DocREModel_KD(args, config, model, num_labels=args.num_labels)    │
  File "/home/yani/disertasi/kd-docre/model.py", line 93, in __init__         │
    self.multihead_attn = MultiHeadAttention(config.hidden_size, 16, kdim=conf│
ig.hidden_size, vdim=config.hidden_size)                                      │
TypeError: __init__() got an unexpected keyword argument 'kdim' 

Could I get any insights for this?

Best regards,

Mohammad

**Comment by WatsonWangZh** [comment]
the module can be found in fairseq repository: https://github.com/facebookresearch/fairseq/blob/main/fairseq/modules/multihead_attention.py

**Comment by tonytan48** [comment]
Hi Mohammad,

Sorry for the late reply. I was working on some other work related to DocRE. This part was not used in the final experiments and I only used them for testing. Thanks for your comment.
