### ISSUE TITLE
I'm confusing about KD-DocRE/scripts/

### ISSUE THREAD

**Issue by bitten-littlesuqirrel** [tonytan48/KD-DocRE#9]
![image](https://user-images.githubusercontent.com/40733610/178309297-c4631a56-bf51-4a46-8d80-1d51cfceceb2.png)
![image](https://user-images.githubusercontent.com/40733610/178309338-776eb61a-8b62-458c-9f7f-4f0719b325bc.png)
Hi,I'm confused about **{model-name}** and **{model-name}.pt** in the picture.

And what's model-name?

**Comment by bitten-littlesuqirrel** [comment]
![image](https://user-images.githubusercontent.com/40733610/178310001-b808b357-bd52-49ba-9a02-84e2fd264900.png)
When I running  **bash scripts/inference_logits_bert.sh**,I meet this bug.

**Comment by tonytan48** [comment]
Thank you for your interest, I was unwell for the past several days due to covid. 
The {model-name} here should be a custom model name by you. It does not necessarily need to end with .pt. So whatever model name that you used in the previous step shall be used here.

**Comment by tonytan48** [comment]
Thank you!
